
image:
  repository: opentext/vertica-k8s
  pullPolicy: IfNotPresent
  tag: ""

local:
  storageClass: gp2
  requestSize: 500Gi

passwordSecret: ""

serviceAccountName: ""

annotations: {}

communal:
  path: ""
  endpoint: ""
  s3ServerSideEncryption: ""
  region: ""

# If your Kubernetes cluster is in the cloud or on a managed service, each Vertica node must operate in the same availability zone.
# https://docs.vertica.com/25.1.x/en/containerized/configuring-communal-storage/
subclusters:
  - name: primary
    size: 3
    serviceType: LoadBalancer
    loadBalancerScheme: internet-facing

dbName: "vertdb"
superUsername: "dbadmin"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

dataChannelEncryption: true

annotations: {}