apiVersion: vertica.com/v1
kind: VerticaDB
metadata:
  name: {{ include "database.fullname" . }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
  annotations:
    {{- include "database.annotations" . | nindent 4 }}
spec:
  local:
    storageClass: {{ .Values.local.storageClass }}
    requestSize: {{ .Values.local.requestSize }}
  serviceAccountName: {{ .Values.serviceAccountName }}
  passwordSecret: {{ .Values.passwordSecret }}
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  imagePullPolicy: {{ .Values.pullPolicy }}
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  communal:
    path: {{ .Values.communal.path }}
    {{- if .Values.communal.endpoint }}
    endpoint: {{ .Values.communal.endpoint }}
    {{- end }}
    {{- if .Values.communal.s3ServerSideEncryption }}
    s3ServerSideEncryption: {{ .Values.communal.s3ServerSideEncryption }}
    {{- end }}
    {{- if .Values.communal.region }}
    region: {{ .Values.communal.region }}
    {{- end }}
  dbName: {{ .Values.dbName }}
  subclusters:
    {{- range .Values.subclusters }}
    - name: {{ .name }}
      size: {{ .size }}
      serviceType: {{ .serviceType }}
      {{- if eq .serviceType "LoadBalancer" }}
      serviceAnnotations:
        service.beta.kubernetes.io/aws-load-balancer-type: external
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
        service.beta.kubernetes.io/aws-load-balancer-scheme: {{ .loadBalancerScheme | default "internet-facing" }}
      {{- end }}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - vertica
              topologyKey: topology.kubernetes.io/zone
    {{- end }}